"""
Django settings for drf_apis project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import socket
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-44h@-%gu3j=4#+w((ixtbvjytuk=e^b96%@64otl%o1!xla8+-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'manifest',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drf_apis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drf_apis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DB_CONFIG = {
#     "name": "EBSDB",
#     "user": "apps",
#     "tns": '(description=(address_list=(address = (protocol = TCP)(host = ebs.example.com)(port = 1521)))(connect_data =(service_name=EBSDB)))',
#     "password": 'apps',
# }

DB_CONFIG = {
    "name": "ORCLCDB",
    "user": "C##MYUSER",
    "tns": '(description=(address_list=(address = (protocol = TCP)(host = 192.168.176.2)(port = 1521)))(connect_data =(service_name=ORCLCDB)))',
    "password": 'password',
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': '(description=(address_list=(address = (protocol = TCP)(host = 192.168.176.2)(port = 1521)))(connect_data =(service_name=ORCLCDB)))',
        'USER': 'C##MYUSER',
        'PASSWORD': 'password',
        'schemas': ['C##MYUSER'],
        'TIME_ZONE': 'America/Los_Angeles',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.oracle',
#         'NAME': '(description=(address_list=(address = (protocol = TCP)(host = ebs.example.com)(port = 1521)))(connect_data =(service_name=EBSDB)))',
#         'USER': 'apps',
#         'PASSWORD': 'apps',
#         'schemas': ['APPS'],
#         'TIME_ZONE': 'America/Los_Angeles',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#CUSTOM VARIABLES
hostname = socket.gethostname()
env = os.environ.get('DJANGO_SETTINGS_MODULE')
DB_USER = "C##MYUSER"
TIMEZONE = "PST"
DB_NAME = "ORCLCDB"

# DB_USER = "apps"
# TIMEZONE = "PST"
# DB_NAME = "EBSDB"

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '0/minute',
        'user': '12/minute'
    },
}